"""add processing_ms to jobs

Revision ID: 7bc48242348d
Revises: b8a3d6fdff1c
Create Date: 2026-05-25 15:43:15.992167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc48242348d'
down_revision: Union[str, Sequence[str], None] = 'b8a3d6fdff1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('processing_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'processing_ms')
    # ### end Alembic commands ###
