"""add user_id to jobs

Revision ID: b8a3d6fdff1c
Revises: e451f6e778b9
Create Date: 2026-05-25 13:16:29.824474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a3d6fdff1c'
down_revision: Union[str, Sequence[str], None] = 'e451f6e778b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
